unbind C-left
unbind C-right
unbind C-up
unbind C-down

bind M-left resize-pane -L
bind M-right resize-pane -R
bind M-up resize-pane -U
bind M-down resize-pane -D

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on
