bind -n M-h resize-pane -L
bind -n M-l resize-pane -R
bind -n M-k resize-pane -U
bind -n M-j resize-pane -D

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

set -sg escape-time 0

set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# hightlight tabs that printed output while unfocused
setw -g monitor-activity on
set  -g visual-activity off
setw -g window-status-activity-style 'fg=#f9e2af bold'

# windows and statusline
setw -g window-status-format         '  #I  #W  '
setw -g window-status-current-format '  #I  #W  '
setw -g window-status-separator      ''
set  -g status-style                 'bg=#d1942a fg=#1e1e2e'
setw -g window-status-style          'bg=#d1942a fg=#1e1e2e'
setw -g window-status-current-style  'bg=#45475a fg=#ffffff bold'

# use active pane dir for window name
setw -g automatic-rename on
set  -g automatic-rename-format '#{?#{==:#{pane_current_path},#{HOME}},~,#{b:pane_current_path}}'
set  -g allow-rename off

bind R source-file ~/.config/tmux/tmux.conf \; display 'reloaded'
